apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: terraform-agent
spec:
  serviceName: terraform-agent
  replicas: 3
  selector:
    matchLabels:
      app: terraform-cloud-agent
  template:
    metadata:
      labels:
        app: terraform-cloud-agent
    spec:
      containers:
        - name: terraform-agent
          image: hashicorp/tfc-agent:latest
          ports:
            - containerPort: 8080
          env:
            - name: TFC_AGENT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: TFC_AGENT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: healthy-organ-tokens
                  key: |
                    {{- if eq (printf "%d" .metadata.name | split "-" | last) "0" -}}
                    token-agent1
                    {{- else if eq (printf "%d" .metadata.name | split "-" | last) "1" -}}
                    token-agent2
                    {{- else -}}
                    token-agent3
                    {{- end }}
