apiVersion: apps/v1
kind: Deployment
metadata:
  name: terraform-agent-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: terraform-cloud-agent
      agent: agent1
  template:
    metadata:
      labels:
        app: terraform-cloud-agent
        agent: agent1
    spec:
      containers:
        - name: terraform-agent
          image: hashicorp/tfc-agent:latest
          ports:
            - containerPort: 8080
          env:
            - name: TFC_AGENT_NAME
              value: agent1
            - name: TFC_AGENT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: healthy-organ-tokens
                  key: token-agent1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: terraform-agent-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: terraform-cloud-agent
      agent: agent2
  template:
    metadata:
      labels:
        app: terraform-cloud-agent
        agent: agent2
    spec:
      containers:
        - name: terraform-agent
          image: hashicorp/tfc-agent:latest
          ports:
            - containerPort: 8080
          env:
            - name: TFC_AGENT_NAME
              value: agent2
            - name: TFC_AGENT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: healthy-organ-tokens
                  key: token-agent2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: terraform-agent-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: terraform-cloud-agent
      agent: agent3
  template:
    metadata:
      labels:
        app: terraform-cloud-agent
        agent: agent3
    spec:
      containers:
        - name: terraform-agent
          image: hashicorp/tfc-agent:latest
          ports:
            - containerPort: 8080
          env:
            - name: TFC_AGENT_NAME
              value: agent3
            - name: TFC_AGENT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: healthy-organ-tokens
                  key: token-agent3
