apiVersion: apps/v1
kind: Deployment
metadata:
  name: terraform-agent
  labels:
    app: terraform-cloud-agent
spec:
  replicas: 1  # Number of replicas for the deployment
  selector:
    matchLabels:
      app: terraform-cloud-agent
  template:
    metadata:
      labels:
        app: terraform-cloud-agent
    spec:
      containers:
        - name: terraform-agent
          image: hashicorp/tfc-agent:latest  # Terraform Cloud Agent Docker Image
          env:
            - name: TFC_AGENT_TOKEN  # The Terraform Cloud agent token
              value: "D1Otggk5bahOww.atlasv1.Iq2FuoEybPG6rEzD4Igiz70pK3ZqxrasQDJ0nPKazBFv8jG7cPz78VJTOD9H2cAQfAA"
            - name: TFC_AGENT_NAME
              value: "agentinpod"
            - name: TFC_AGENT_LOG_LEVEL
              value: "trace"
          ports:
            - containerPort: 8080
      restartPolicy: Always



