apiVersion: apps/v1
kind: Deployment
metadata:
  name: terraform-agent
  labels:
    app: terraform-cloud-agent
spec:
  replicas: 1  # Number of replicas for the deployment
  revisionHistoryLimit: 2  # Retain only 2 old ReplicaSets
  selector:
    matchLabels:
      app: terraform-cloud-agent
  template:
    metadata:
      labels:
        app: terraform-cloud-agent
    spec:
      restartPolicy: Always
      containers:
        - name: terraform-agent-1
          image: hashicorp/tfc-agent:latest
          env:
            - name: TFC_AGENT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: healthy-organ-tokens
                  key: token-agent1  # Referencing the first token from the Secret
            - name: TFC_AGENT_NAME
              value: "agent-1"
          ports:
            - containerPort: 8080
        
        - name: terraform-agent-2
          image: hashicorp/tfc-agent:latest
          env:
            - name: TFC_AGENT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: healthy-organ-tokens
                  key: token-agent2  # Referencing the second token from the Secret
            - name: TFC_AGENT_NAME
              value: "agent-2"
          ports:
            - containerPort: 8080
        
        - name: terraform-agent-3
          image: hashicorp/tfc-agent:latest
          env:
            - name: TFC_AGENT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: healthy-organ-tokens
                  key: token-agent3  # Referencing the third token from the Secret
            - name: TFC_AGENT_NAME
              value: "agent-3"
          ports:
            - containerPort: 8080


